# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

name: 'CHART README TABLE GENERATOR'

on:
  pull_request_target:
    branches:
      - main
    paths:
      # specify this for now until we get the readme table for all charts
      - 'stable/enterprise/values.yaml'
      - 'stable/feeds/values.yaml'
# Remove all permissions by default
permissions: {}
jobs:
  update-readme-metadata:
    env:
      REPO: "${{ github.repository }}"
      REPO_NAME: "${{ github.event.repository.name }}"
      TARGET_BRANCH: "${{ github.event.pull_request.base.ref }}"
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@8ca2b8b2ece13480cda6dacd3511b49857a23c09 # v2.5.1
        with:
          egress-policy: audit

      - name: Install readme-generator-for-helm
        run: npm install -g @bitnami/readme-generator-for-helm

      - name: Checkout charts
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          path: ${{ github.repository }}
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
          token: ${{ secrets.CI_WRITE_GITHUB_TOKEN }}

      - run: cd "${REPO}" && git fetch origin ${TARGET_BRANCH}

      - name: Execute readme-generator-for-helm
        run: |
          cd "${REPO}"
          files_changed="$(git diff --name-only origin/${TARGET_BRANCH} | sort | uniq)"
          # Adding || true to avoid "Process exited with code 1" errors
          charts_dirs_changed="$(echo "$files_changed" | xargs dirname | grep -o "stable/[^/]*" | sort | uniq || true)"

          for chart in ${charts_dirs_changed}; do
            if [[ "$chart" == "stable/enterprise" || "$chart" == "stable/feeds" ]]; then
              echo "Updating README.md for ${chart}"
              readme-generator --values "${chart}/values.yaml" --readme "${chart}/README.md" --schema "/tmp/schema.json"
            else
                echo "'chart' is not equal to 'stable/enterprise' or 'stable/feeds'. Moving on."
            fi
          done
      - name: Push changes
        run: |
          # Push all the changes
          cd "${REPO}"
          if git status -s | grep stable; then
            git config user.name "Anchore BitnamiReadmeGenerator"
            git config user.email "anchoreops-ci@anchore.com"
            git add stable && git commit -m "Update README.md with readme-generator-for-helm" --signoff && git push
          fi
