name: Release Charts to charts.anchore.io

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  release:
    permissions:
      contents: write  # for helm/chart-releaser-action to push chart release and create a release
    env:
      REPO: "${{ github.repository }}"
      REPO_NAME: "${{ github.event.repository.name }}"
      TARGET_BRANCH: "${{ github.event.pull_request.base.ref }}"
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@8ca2b8b2ece13480cda6dacd3511b49857a23c09 # v2.5.1
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0

      - name: Fetch history
        run: git fetch --prune --unshallow

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Add Anchore Helm repo
        run: |
          helm repo add anchore https://charts.anchore.io/stable
          helm repo add bitnami https://charts.bitnami.com/bitnami

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@be16258da8010256c6e82849661221415f031968 # v1.5.0
        with:
          charts_dir: stable
          charts_repo_url: https://charts.anchore.io
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
